name: Docker Build and Push

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::$(cat version.txt)

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          mosliu/url-checker:latest
          mosliu/url-checker:${{ steps.get_version.outputs.VERSION }}
          mosliu/url-checker:${{ steps.get_version.outputs.VERSION }}-${{ steps.date.outputs.date }}
          mosliu/url-checker:${{ github.sha }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
